### PR TITLE
recognize parent.relativePath

### LINKED ISSUE #610: Sometimes the identifier group value will show "undefined"
**To Reproduce**
1. Clone and open [spring-hadoop-samples](https://github.com/spring-projects/spring-hadoop-samples.git)
2. Click on the project item and expand the plugins node
3. See error

**Environments (please complete the following information as much as possible):**

- OS: Windows 10/Mac OS 10.15.7
- VS Code version: 1.55.0
- Extension version 0.28.0

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Eskibear**
To fix #610 .
Also fixing a potential issue: properties from parent projects with custom `relativePath` were not recognized.

E.g. 
in `../parent/pom.xml`
```
	<properties>
		<testProp>CUSTOM_PROPERTY</testProp>
...
```

in `pom.xml`
```
	<name>Spring Hadoop Samples - Hive - ${testProp}</name>
```
Now we get:
image

### CODE REVIEW

File: src/explorer/model/MavenProject.ts [hunk 1]
```diff
@@ -51,7 +51,8 @@ export class MavenProject implements ITreeItem {
     }
 
     public get groupId(): string {
-        return this._pom?.project?.groupId?.[0] ?? this.parent?.groupId;
+        return this._pom?.project?.groupId?.[0] ?? this._pom?.project?.parent?.[0]?.groupId?.[0];
+        //this.parent?.groupId;
```
Comment (jdneo) [inline src/explorer/model/MavenProject.ts:55]: nit: remove?

**Review by jdneo — APPROVED** [review]

File: src/explorer/model/MavenProject.ts (hunk 1 above)
Comment (Eskibear) [reply src/explorer/model/MavenProject.ts:55]: I'd prefer to append `?? this.parent?.groupId` althrough it may not be necessary...
