### PR TITLE
fix: diagnostics do not refresh after editing pom file

### LINKED ISSUE #692: diagnostics not refresh after editing pom.xml
**Describe the bug**
error message in Problems channel for conflict dependencies has the wrong location after editing pom.xml

**Expected behavior**
refresh diagnostics when the pom.xml has been changed

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Melody618**
fix #692, refresh diagnostics if the pom file has changed.

Also apply adaptive debounce to improve the performance.

### CODE REVIEW

**Comment by Melody618** [comment]
still working on adaptive debounce

**Comment by jdneo** [comment]
Debouncing part looks good to me, while I didn't quite get when `conflictNodes` needs to be a member of `DiagnosticProvider`

**Comment by Eskibear** [comment]
@jdneo please take a look at the moving avg impl.

**Comment by jdneo** [comment]
As I said, the debouncing part looks good to me. But I'm not sure persisting `conflictNodes` inside `diagnosticProvider` is a good practice. 

Does that mean all the `conflictNodes` belongs to the same uri?

**Comment by Melody618** [comment]
> Does that mean all the conflictNodes belongs to the same uri?

Yes, one pom file, one uri, and the `conflictNodes` hold all conflict dependencies in this pom file.

**Comment by Melody618** [comment]
now `DiagnosticProvider` is workspace level and it provides diagnostics for all pom files. However, it will hold only conflict nodes for one pom file and it is a module level.

I am working to refine the structure: remove `conflictNodes`  and add a utility function to link uri and conflict nodes.

File: src/DiagnosticProvider.ts [hunk 1]
```diff
@@ -16,22 +20,44 @@ class DiagnosticProvider {
...
+        context.subscriptions.push(vscode.workspace.onDidChangeTextDocument(
+        async e => {
+            if (e.document.fileName.endsWith("pom.xml")) {
+                await this.debouncedRefresh(e.document.uri);
+            }
         }));
     }
 
-    public async refreshDiagnostics(uri: vscode.Uri, conflictNodes: Dependency[]): Promise<vscode.Diagnostic[]> {
-        this.map.clear();
```
Comment (Melody618) [inline src/DiagnosticProvider.ts:26]: should not clear map because refresh diagnostics for one pom file should not change diagnostics of other pom files.

File: src/DiagnosticProvider.ts [hunk 2]
```diff
@@ -44,9 +45,14 @@ class DiagnosticProvider {
     }
 
     public async refreshDiagnostics(uri: vscode.Uri): Promise<void> {
-        this.map.clear();
         const diagnostics: vscode.Diagnostic[] = [];
-        for (const node of this.conflictNodes) {
+        const project: MavenProject | undefined = mavenExplorerProvider.getMavenProject(uri.fsPath);
+        if (project === undefined) {
+            throw new Error("Failed to get maven projects.");
```
Comment (jdneo) [inline src/DiagnosticProvider.ts:51]: plural should not be used here. A uri should only map to one project, right?

**Review by jdneo — APPROVED** [review]
